= Caching

A PWA is usually a view on data hosted on a server somewhere. This means when a user loads a page for the first time, requests will be sent by the server hosting the PWA (see also xref:SSR.adoc[SSR]) to the server that hosts the data. The page will be rendered and sent to the client where it can be viewed. The data that is required to create the current view is sent along with it and the client side storage will be hydrated with the fresh data. This allows the user to navigate the page and views without having to fetch new data from the backend. Sometimes you don’t want to fetch new data from the backend to refresh a page or a view. Additionally you might want to control which data is available offline for various reasons (eg. it could be a big chunk of data). This is where caching comes in.

When you have a component that extends xref:components/FSXABaseComponent.adoc[FSXABaseComponent] you get access to the `setStoredItem` and `getStoredItem` functions. These functions basically utilize the vuex store to save data for you. You have to pick a string as key and later you can retrieve your items from the store using the key. You can set a time to live in milliseconds, the default being `300000` or 5 minutes. When this time runs out, your cache is invalidated and the `getStoredItem` function will return `undefined`.

It is up to you to write your component in such a manner, that the data is refetched if the cache is invalidated. Here are two examples of what this could look like.

SFC-Example

[source,xml]
----
<template>
  <div v-if="myFreshData()">{{ myFreshData() }}</div>
</template>
<script>
  export default {
    extends: FSXABaseComponent,
    data() {
      return {
        myFreshData() {
          return this.getStoredItem('myFreshData')
        }
      }
    },
    mounted() {
      this.fetchData()
    },
    methods: {
      async fetchData() {
        const data = //make your async request to the server containing the data here
        this.setStoredItem('myFreshData', data, 100000)
      }
    },
  }
</script>
----

TSX-Example

[source,javascript]
----
@Component({
  name: 'MyComponent',
})
class MyComponent extends FSXABaseComponent<{}>{
  mounted() {
    if(!this.myData()){
      this.fetchData()
    } 
  }
  async fetchData() {
    const data = //make your async request to the server containing the data here
    this.setStoredItem('myFreshData', data, 100000)
  }

  get myData(){
    return this.getStoredItem('myFreshData') || null
  }
  render(){
    return(
      <div>
        this.myData ? myData : null
      </div>
    )
  }
}
----
