= Introduction

:moduledir: ..
:imagesdir: {moduledir}/images

== General

The FSXA PWA is a project that demonstrates how to build a _Progressive Web App_ that is consuming contents created and continuosly updated with the enterprise content management system https://www.e-spirit.com/en/product/firstspirit-dxp/enterprise-cms/[FirstSpirit]. It is part of the https://docs.e-spirit.com/module/fsxa/[FirstSpirit Experience Accelerator], a set of projects allowing you to set up a state-of-the-art web presence in a fraction of the time required previously or with competing products.

== Projects used

The FSXA PWA connects to several other projects:

* https://github.com/e-Spirit/fsxa-ui[FSXA-UI]/ Component Library
* https://github.com/e-Spirit/fsxa-nuxt-module[FSXA-Nuxt-Module]
* https://github.com/e-Spirit/fsxa-pattern-library[FSXA-Pattern-Library]
* https://github.com/e-Spirit/fsxa-api[FSXA-API]
* http://docs.e-spirit.com/tpp/[Omnichannel Manager]
* https://docs.e-spirit.com/module/caas/CaaS_Platform_Documentation_EN.html[FirstSpirit CaaS]

The role of each of these is best seen in the architecture layout depicted below:

== Architecture

image:FSXA_PWA_Architecture.svg[FSXA Architecture]

=== FSXA UI / Component Library

FSXA UI is a component library used by the FSXA PWA. It contains all components used in the sample project. The Component Library is maintained and continuously extended by the e-Spirit AG.

=== FSXA NUXT Module

The FSXA Nuxt Module integrates the FSXA Pattern Library on a Node.js server. This Node.js server with NUXT is used for Server Side Rendering.

=== FSXA Pattern Library

The FSXA Pattern Library manages the connection to the "`outside world`". This means it handles the data coming from the CaaS (the FSXA-API acting as an intermediate stage) and provides this data to the PWA. It also connects the PWA to the Omnichannel-Manager to have components editable in the FirstSpirit ContentCreator.

=== FSXA API

In headless environments, the editorial content from FirstSpirit is provided via the CaaS. Additionally, the site’s structure can be accessed via the Navigation Service (here considered part of the CaaS).

To make using these two services as easy as possible, we have developed the FSXA API. This project already provides a rich API to communicate with both services in a standardized way. It also transforms the responses of the CaaS and the Navigation Service and enriches them with other useful data.

For example, it converts the Navigation Service tree structure into easy to use maps and also extracts the start page directly.

The responses of the CaaS are transformed as well and unnecessary information for the frontend is removed.

=== Omnichannel Manager

The Omnichannel Manager provides the FirstSpirit ContentCreator’s advanced editing and workflow capabilities to your PWA.

=== FirstSpirit CaaS

The https://docs.e-spirit.com/module/caas/CaaS_Platform_Documentation_EN.html[FirstSpirit CaaS] (Content as a Service) provides all editorial content from your FirstSpirit project. Your project’s structural data is provided as well, via the https://docs.e-spirit.com/module/caas/CaaS_Platform_Documentation_EN.html[Navigation Service].

== Deployment

By default customers are provided with a _DQP_ setup: _Development_, _Quality Assurance_, and _Production_. They get a _git_ repository with corresponding branches. In the FSXA default setup all that is required to deploy changes to a PWA is pushing changes - the PWA will automatically be built and deployed. With FirstSpirit’s pattern of "`preview`" and "`release`" states for project contents this setup leeds to three times two = six PWA instances per project.

Technology used "`behind the scenes`":

* https://kubernetes.io/[Kubernetes]
* https://helm.sh/[Helm]
* https://rancher.com/[Rancher]

image:ccd_tools.svg[CCD Tools,400]

=== Running the application in a production environment
In the deployment process e-Spirit uses Docker to containerize the applications.
To verify your pwa is compliant to the provided Dockerfile, you can use the Dockerfile.template.
You just need to change the template file in such way, that your custom env parameters are set accordingly to you `.env` file.

Once you have updated your template just rename the file to `Dockerfile`.
If you then execute `docker build -t my-pwa .` and the image could be built successfully, 
your application will be compliant with the e-Spirit build pipeline.
To ensure the created image runs successfully, you can also run it locally with `docker run -p XXXX:3000 my-pwa`. 
Where XXXX can be any free port. After the container is running, you can open localhost:XXXX in a browser and the the pwa should show up.

Please note: 
Due to security aspects providing a custom Dockerfile will stop the build pipeline. 
Make sure not to commit a Dockerfile to your project's repository.
