# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master, next, alpha and beta branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # Only release on push to master
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install
      run: npm install --no-optional

    - name: Release
      run: npm run semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
